---
name: "¡Hola Javascript!"
locale: es
type: learning
beta: false
teacher_info: ''
language: javascript
id_format: "%05d"
order:
- 1
- 2
- 15
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
private: false
