---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: En el lenguaje de programación _Java_.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: En el personaje de _Star Wars_, Jabba el hutt.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: En la Isla de Java.
  checked: false
name: "¡Ya va Script!"
