---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
language: javascript
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_matches
  regexp: '"caracol".startsWith("cara") && "caracol".endsWith("col")'
name: No olvidemos los booleanos
